=== gil-l/LUP/resources/qa/classification/map/WordNetMapSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:complexType name="CategoryType">
    	<xsd:sequence minOccurs="0" maxOccurs="unbounded">
    		<xsd:element name="target" type="TargetType" minOccurs="0" maxOccurs="unbounded">
    		</xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
    </xsd:complexType>    
    <xsd:complexType name="TargetType">
    	<xsd:attribute name="offset" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="POS" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="words" type="xsd:string"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="MapType">
    	<xsd:sequence>
    		<xsd:element name="category" type="CategoryType" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="wn-version" type="xsd:string"></xsd:attribute>
    </xsd:complexType>
    <xsd:element name="map" type="MapType"></xsd:element>
</xsd:schema>

=== gil-l/LUP/resources/qa/classification/map/WordNetMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<map wn-version="3.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="WordNetMapSchema.xsd">
	<!-- ABBREVIATION -->
	<category name="ABBREVIATION_ABBREVIATION">
		<target offset="7091587" POS="noun" words="abbreviation -- (a shortened form of a word or phrase)"/>
		<target offset="7091902" POS="noun" words="acronym -- (a word formed from the initial letters of the several words in the name)"/>
	</category>
	<category name="ABBREVIATION_EXPANSION" />
	<!-- DESCRIPTION -->
	<category name="DESCRIPTION_DEFINITION">
		<target offset="6601327" POS="noun" words="meaning, significance, signification, import -- (the message that is intended or expressed or signified)" />
		<target offset="5919866" POS="noun" words="meaning, substance -- (the idea that is intended)" />
		<target offset="6744396" POS="noun" words="definition -- (a concise explanation of the meaning of a word or phrase or symbol)" />
		<target offset="957378" POS="verb" words="define -- (give a definition for the meaning of a word)" />
	</category>
	<category name="DESCRIPTION_DESCRIPTION">
		<target offset="13559177" POS="noun" words="origin -- (the source of something's existence or from which it derives or is derived)" />
		<target offset="4748836" POS="noun" words="difference -- (the quality of being unlike or dissimilar)" />
		<target offset="987071" POS="noun" words="describe, depict, draw -- (give a description of)" />
	</category>
	<category name="DESCRIPTION_MANNER" />
	<category name="DESCRIPTION_REASON">
		<target offset="9178999" POS="noun" words="reason, ground -- (a rational motive for a belief or action)" />
		<target offset="7326557" POS="noun" words="cause -- (events that provide the generative force that is the origin of something)" />
	</category>
	<!-- ENTITY -->
	<category name="ENTITY_ANIMAL">
		<target offset="15388" POS="noun" words="animal, animate_being, beast, brute, creature, fauna -- (a living organism characterized by voluntary movement)" />
		<target offset="7993929" POS="noun" words="animal_group -- (a group of animals)"/>
	</category>
	<category name="ENTITY_BODY">
		<target offset="5220461" POS="noun" words="body_part -- (any part of an organism such as an organ or extremity)" />
	</category>
	<category name="ENTITY_COLOR">
		<target offset="4956594" POS="noun" words="color, colour, coloring, colouring -- (a visual attribute of things that results from the light they emit or transmit or reflect)" />
	</category>	
	<category name="ENTITY_CREATIVE">
		<target offset="6619065" POS="noun" words="show -- (a social event involving a public performance or entertainment)" />
		<target offset="7020895" POS="noun" words="music -- (an artistic form of auditory communication incorporating instrumental or vocal tones in a structured and continuous manner)" />
		<target offset="6410904" POS="noun" words="book -- (a written work or composition that has been published (printed on pages bound together))" />
		<target offset="6362953" POS="noun" words="writing, written_material, piece_of_writing -- (the work of a writer; anything expressed in letters of the alphabet (especially when considered from the point of view of style and effect))" /> 
		<target offset="3038595" POS="noun" words="classic -- (a creation of the highest excellence)" /> 
		<target offset="2743547" POS="noun" words="art, fine_art -- (the products of human creativity; works of art collectively)" /> 
		<target offset="6254669" POS="noun" words="medium -- (a means or instrumentality for storing or communicating information)" /> 
		<target offset="7985825" POS="noun" words="trilogy -- (a set of three literary or dramatic works related in subject or theme)" />
		<target offset="6399503" POS="noun" words="sequel, continuation -- (a part added to a book or play that continues and extends it)" />
	</category>
	<category name="ENTITY_CURRENCY">
		<target offset="13385913" POS="noun" words="currency -- (the metal or paper medium of exchange that is presently used)" />
	</category>
	<category name="ENTITY_MEDICINE">
<!--  ADD MEDICINE -->
		<target offset="14299637" POS="noun" words="symptom -- ((medicine) any sensation or change in bodily function that is experienced by a patient and is associated with a particular disease)" />
		<target offset="3247620" POS="noun" words="drug -- (a substance that is used as a medicine or narcotic)" />
		<target offset="657604" POS="noun" words="medical_care, medical_aid -- (professional treatment for illness or injury)" />
		<target offset="14034177" POS="noun" words="physical_condition, physiological_state, physiological_condition -- (the condition or state of the body or bodily functions)" />
	</category>
	<category name="ENTITY_EVENT">
		<target offset="29378" POS="noun" words="event -- (something that happens at a given place and time)" />
		<target offset="8307589" POS="noun" words="meeting, group_meeting -- (a formally arranged gathering)" />
	</category>
	<category name="ENTITY_FOOD">
		<target offset="21265" POS="noun" words="food, nutrient -- (any substance that can be metabolized by an animal to give energy and build tissue)" />
		<target offset="7555863" POS="noun" words="food, solid_food -- (any solid substance (as opposed to liquid) that is used as a source of nourishment)" />
		<target offset="13134947" POS="noun" words="fruit -- (the ripened reproductive body of a seed plant)"/>
		<target offset="7578363" POS="noun" words="helping, portion, serving -- (an individual quantity of food or drink taken as part of a meal)" />		
	</category>	
	<category name="ENTITY_INSTRUMENT">
		<target offset="3800933" POS="noun" words="musical_instrument, instrument -- (any of various devices or contrivances that can be used to produce musical tones or sounds)" />
	</category>
	<category name="ENTITY_LANGUAGE">
		<target offset="6282651" POS="noun" words="language, linguistic_communication -- (a systematic means of communicating by the use of sounds or conventional symbols)"/>
		<target offset="7155661" POS="noun" words="dialect, idiom, accent -- (the usage or vocabulary that is characteristic of a specific group of people)"/>
	</category>
	<category name="ENTITY_LETTER">
		<target offset="6828818" POS="noun" words="letter, letter_of_the_alphabet, alphabetic_character -- (the conventional characters of the alphabet used to represent speech)"/>
		<target offset="6488880" POS="noun" words="character_set -- (an ordered list of characters that are used together in writing or printing)"/>		
	</category>	
	<category name="ENTITY_PLANT">
		<target offset="17222" POS="noun" words="plant, flora, plant_life -- ((botany) a living organism lacking the power of locomotion)"/>
		<target offset="8436759" POS="noun" words="vegetation, flora, botany -- (all the plant life in a particular region or period)"/>
	</category>
	<category name="ENTITY_PRODUCT">
		<target offset="6845599" POS="noun" words="trade_name, brand_name, brand, marque -- (a name given to a product or service)" />
		<target offset="3748886" POS="noun" words="merchandise, ware, product -- (commodities offered for sale)" />
	</category>	
	<category name="ENTITY_RELIGION">
		<target offset="5946687" POS="noun" words="religion, faith, religious_belief -- (a strong belief in a supernatural power or powers that control human destiny)"/>
		<target offset="8151490" POS="noun" words="cult -- (followers of an exclusive system of religious beliefs and practices)"/>
		<target offset="5948264" POS="noun" words="ult, cultus, religious_cult -- (a system of religious beliefs and rituals)"/>
	</category>
	<category name="ENTITY_SPORT">
		<target offset="523513" POS="noun" words="sport, athletics -- (an active diversion requiring physical exertion and competition)"/>
		<target offset="455599" POS="noun" words="game -- (a contest with rules to determine a winner)"/>
		<target offset="430606" POS="noun" words="game -- (an amusement or pastime)"/>
		<target offset="624738" POS="noun" words="exercise, exercising, physical_exercise, physical_exertion, workout -- (the activity of exerting your muscles in various ways to keep fit)"/>
	</category>
	<category name="ENTITY_SUBSTANCE">
		<target offset="19613" POS="noun" words="substance -- (the real physical matter of which a person or thing consists)"/>
	</category>
	<category name="ENTITY_SYMBOL">
		<target offset="6806469" POS="noun" words="symbol -- (an arbitrary sign (written or printed) that has acquired a conventional significance)" />
	</category>
	<category name="ENTITY_TECHNIQUE">
		<target offset="5665146" POS="noun" words="technique -- (a practical method or art applied to some particular task)" />
		<target offset="941140" POS="noun" words="approach, attack, plan_of_attack -- (ideas or actions intended to deal with a problem or situation)" />	
		<target offset="4928903" POS="noun" words="manner, mode, style, way, fashion -- (how something is done or how it happens)" />	
		<target offset="5660268" POS="noun" words="method -- (a way of doing something, especially a systematic way)" />	
		<target offset="1023820" POS="noun" words="procedure, process -- (a particular course of action intended to achieve a result)" />	
		<target offset="5902545" POS="noun" words="plan_of_action -- (a plan for actively doing something)" />		
	</category>
	<category name="ENTITY_TERM">
		<target offset="6303888" POS="noun" words="term -- (a word or expression used for some particular thing)" />
	</category>
	<category name="ENTITY_VEHICLE">
		<target offset="4524313" POS="noun" words="vehicle -- (a conveyance that transports people or objects)" />
	</category>
	<category name="ENTITY_WORD">
		<target offset="6286395" POS="noun" words="word -- (a unit of language that native speakers can identify)" />
	</category>
	<category name="ENTITY_OTHER">
